services:
  - type: web
    name: arbit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free

  - type: worker
    name: pinger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python pinger.py
    plan: free
